// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4enC2waE49F04_CmUE5LwL4AR_sYASLs',
    appId: '1:694827449903:web:81cb1b5bf1f236b7d050da',
    messagingSenderId: '694827449903',
    projectId: 'chat-b2d78',
    authDomain: 'chat-b2d78.firebaseapp.com',
    storageBucket: 'chat-b2d78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsBrFKwftFcaP-gpGrY4i-mhpseWePSL0',
    appId: '1:694827449903:android:a77e05c43230a71bd050da',
    messagingSenderId: '694827449903',
    projectId: 'chat-b2d78',
    storageBucket: 'chat-b2d78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0hTsL-eXam_NZ0-t2rLDv2MJc1gVpaI',
    appId: '1:694827449903:ios:0caca4b88c9c9d8ad050da',
    messagingSenderId: '694827449903',
    projectId: 'chat-b2d78',
    storageBucket: 'chat-b2d78.appspot.com',
    iosClientId: '694827449903-9lod7prdj5m4pol5gko54gvudvrpo3jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
